### ISSUE TITLE
No location received

### ISSUE THREAD

**Issue by carlberg74** [brocaar/chirpstack-geolocation-server#1]
I have just setup the lora-geo-server and set the subscription_key in the configuration, is that all that is needed to configure?

Having messages coming in via iBTS gateway and I can see that long/lat is set on the gateway.
I cant see anything in the lora-geo-server log and I don't get anything on the mqtt..
Have set log_level=5.. 

I was expecting location information would come back on a "location" topic.

Cheers
-Anders

**Comment by sagar-patel-sls** [comment]
Hii,
i am also not getting location, i already setup `lora-geo-server` and `subscription key` in the configuration also setup `lora-geo-server` in `loraserver` configuration.

still i cannot get location information on **location** topic

**Comment by brocaar** [comment]
You need at least 3 gateways with fine-timestamp support (like the iBTS). Do you meet this requirement?

**Comment by carlberg74** [comment]
ok, understand.
But is there any logging that we can turn on to see the information going between the lora-geo-server and the semtech portal?

or is there simply nothing sent until we have 3+ iBTS gateways?

**Comment by brocaar** [comment]
The latter case. I believe LoRa Server won't even call the LoRa Geo Server in this case.
